
package:
  name: sample_project
  version: 0.0.2

source:
  path: ..

build:
  number: 6

about:
  home: https://anaconda.org/
  license: Creative Commons Attribution 4.0 International License.
  summary: 'smallest packagable project'
